version: "3.7"

services:

    agent:
        build: .
        command: bash -c "prefect agent start --name $$(uuid) --label development"
        volumes:
            - /srv/docker/prefect/flows:/root/.prefect/flows
            - type: bind
              source: ./config.toml
              target: /root/.prefect/config.toml
              read_only: true
