name: 🚀 Pre-release to staging (developers-only)
description: Issue to plan and log pre-release from master to staging deploy (including staging hotfixes)
labels: ["t:maintenance", "release"]
assignees: ["pcrespov"]
body:
  - type: dropdown
    id: prerelease_kind
    attributes:
      label: What kind of pre-release?
      options:
        - Staging
        - Hotfix to Staging
  - type: input
    id: sprint_name
    attributes:
      label: Sprint Name
      description: Name of the sprint in camelcase
      placeholder: ex. ResistanceIsFutile
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Pre-release version
      description: Pre-release count (>=1)
      placeholder: ex. 9
    validations:
      required: true
  - type: input
    id: commit_sha
    attributes:
      label: Commit SHA
      description: |
        Points to the commit from which the release takes placeholder:
        IMPORTANT: make sure t (i.e. tests passed and images were built and pushed)
      placeholder: 7d9dcc313f9ced0bd1e6508363148841683b6d7c
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Did the commit CI suceeded?
      description: Please make sure that the CI of the selected commit in https://github.com/ITISFoundation/osparc-simcore/commits/master
      options:
        - label: The commit CI succeeded.
          required: true
