name: 🚀 Pre-release to staging (developers-only)
description: Issue to plan and log pre-release from master to staging deploy (including staging hotfixes)
labels: ["t:maintenance", "release"]
assignees: ["pcrespov"]
body:
  - type: dropdown
    id: prerelease_kind
    attributes:
      label: What kind of pre-release?
      options:
        - Staging
        - Hotfix to Staging
  - type: input
    id: sprint_name
    attributes:
      label: Sprint Name
      description: Name of the sprint in camelcase
      placeholder: ex. ResistanceIsFutile
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Pre-release version
      description: Pre-release count (>=1)
      placeholder: ex. 9
    validations:
      required: true
  - type: input
    id: commit_sha
    attributes:
      label: Commit SHA
      description: |
        Points to the commit from which the release takes placeholder:
        IMPORTANT: make sure the commit CI is ✅ before releasing (i.e. tests passed and images were built and pushed)
      placeholder: 7d9dcc313f9ced0bd1e6508363148841683b6d7c
    validations:
      required: true
  - type: textarea
    attributes:
      label: Planned changes
      description: |
        After describing the changes, please connect tohttps://github.com/ITISFoundation/osparc-issues/issues/675

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      value: Please connect this case to the Epic https://github.com/ITISFoundation/osparc-issues/issues/675
    validations:
      required: false
