name: 🚀 Release to production  (developers-only)
description: "Creates an issue to release from staging to production"
title: 🚀 Release vX.X.0
labels:
  - release
assignees:
  - pcrespov
body:
  - type: textarea
    attributes:
      label: Motivation
      description: A short explanation of why this release
    validations:
      required: false
