version: "3.8"
services:
  postgres:
    image: "postgres:10"
    init: true
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - sandbox_postgres_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 16000000000
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username",
          "${POSTGRES_USER}",
          "--dbname",
          "${POSTGRES_DB}"
        ]
      interval: 15s
      retries: 5

  adminer:
    image: adminer
    init: true
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=json-column
    ports:
      - "18080:8080"

volumes:
  sandbox_postgres_data: {}
