# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServiceInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, status: str=None, api_version: str=None, version: str=None):  # noqa: E501
        """ServiceInfo - a model defined in Swagger

        :param name: The name of this ServiceInfo.  # noqa: E501
        :type name: str
        :param status: The status of this ServiceInfo.  # noqa: E501
        :type status: str
        :param api_version: The api_version of this ServiceInfo.  # noqa: E501
        :type api_version: str
        :param version: The version of this ServiceInfo.  # noqa: E501
        :type version: str
        """
        self.swagger_types = {
            'name': str,
            'status': str,
            'api_version': str,
            'version': str
        }

        self.attribute_map = {
            'name': 'name',
            'status': 'status',
            'api_version': 'api_version',
            'version': 'version'
        }

        self._name = name
        self._status = status
        self._api_version = api_version
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceInfo of this ServiceInfo.  # noqa: E501
        :rtype: ServiceInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ServiceInfo.


        :return: The name of this ServiceInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ServiceInfo.


        :param name: The name of this ServiceInfo.
        :type name: str
        """

        self._name = name

    @property
    def status(self) -> str:
        """Gets the status of this ServiceInfo.


        :return: The status of this ServiceInfo.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ServiceInfo.


        :param status: The status of this ServiceInfo.
        :type status: str
        """

        self._status = status

    @property
    def api_version(self) -> str:
        """Gets the api_version of this ServiceInfo.


        :return: The api_version of this ServiceInfo.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version: str):
        """Sets the api_version of this ServiceInfo.


        :param api_version: The api_version of this ServiceInfo.
        :type api_version: str
        """

        self._api_version = api_version

    @property
    def version(self) -> str:
        """Gets the version of this ServiceInfo.


        :return: The version of this ServiceInfo.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this ServiceInfo.


        :param version: The version of this ServiceInfo.
        :type version: str
        """

        self._version = version
