# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2022-05-23T22:31:08+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Field


class StuffGet(BaseModel):
    int: int = Field(..., gt=33, title="Int")
    link: AnyUrl = Field(..., max_length=65536, min_length=1, title="Link")
