# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2022-05-23T22:29:23+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class StuffGet(BaseModel):
    int: int = Field(..., gt=33, title="Int")
