# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Manufacturer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, home_page: str=None, phone: str=None):  # noqa: E501
        """Manufacturer - a model defined in Swagger

        :param name: The name of this Manufacturer.  # noqa: E501
        :type name: str
        :param home_page: The home_page of this Manufacturer.  # noqa: E501
        :type home_page: str
        :param phone: The phone of this Manufacturer.  # noqa: E501
        :type phone: str
        """
        self.swagger_types = {
            'name': str,
            'home_page': str,
            'phone': str
        }

        self.attribute_map = {
            'name': 'name',
            'home_page': 'homePage',
            'phone': 'phone'
        }

        self._name = name
        self._home_page = home_page
        self._phone = phone

    @classmethod
    def from_dict(cls, dikt) -> 'Manufacturer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Manufacturer of this Manufacturer.  # noqa: E501
        :rtype: Manufacturer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Manufacturer.


        :return: The name of this Manufacturer.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Manufacturer.


        :param name: The name of this Manufacturer.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def home_page(self) -> str:
        """Gets the home_page of this Manufacturer.


        :return: The home_page of this Manufacturer.
        :rtype: str
        """
        return self._home_page

    @home_page.setter
    def home_page(self, home_page: str):
        """Sets the home_page of this Manufacturer.


        :param home_page: The home_page of this Manufacturer.
        :type home_page: str
        """

        self._home_page = home_page

    @property
    def phone(self) -> str:
        """Gets the phone of this Manufacturer.


        :return: The phone of this Manufacturer.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this Manufacturer.


        :param phone: The phone of this Manufacturer.
        :type phone: str
        """

        self._phone = phone
