# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, description: str=None, created_date: str=None, modified_date: str=None):  # noqa: E501
        """ProjectItem - a model defined in Swagger

        :param id: The id of this ProjectItem.  # noqa: E501
        :type id: str
        :param name: The name of this ProjectItem.  # noqa: E501
        :type name: str
        :param description: The description of this ProjectItem.  # noqa: E501
        :type description: str
        :param created_date: The created_date of this ProjectItem.  # noqa: E501
        :type created_date: str
        :param modified_date: The modified_date of this ProjectItem.  # noqa: E501
        :type modified_date: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'description': str,
            'created_date': str,
            'modified_date': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'created_date': 'createdDate',
            'modified_date': 'modifiedDate'
        }

        self._id = id
        self._name = name
        self._description = description
        self._created_date = created_date
        self._modified_date = modified_date

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProjectItem of this ProjectItem.  # noqa: E501
        :rtype: ProjectItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ProjectItem.


        :return: The id of this ProjectItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ProjectItem.


        :param id: The id of this ProjectItem.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ProjectItem.


        :return: The name of this ProjectItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProjectItem.


        :param name: The name of this ProjectItem.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ProjectItem.


        :return: The description of this ProjectItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProjectItem.


        :param description: The description of this ProjectItem.
        :type description: str
        """

        self._description = description

    @property
    def created_date(self) -> str:
        """Gets the created_date of this ProjectItem.


        :return: The created_date of this ProjectItem.
        :rtype: str
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date: str):
        """Sets the created_date of this ProjectItem.


        :param created_date: The created_date of this ProjectItem.
        :type created_date: str
        """

        self._created_date = created_date

    @property
    def modified_date(self) -> str:
        """Gets the modified_date of this ProjectItem.


        :return: The modified_date of this ProjectItem.
        :rtype: str
        """
        return self._modified_date

    @modified_date.setter
    def modified_date(self, modified_date: str):
        """Sets the modified_date of this ProjectItem.


        :param modified_date: The modified_date of this ProjectItem.
        :type modified_date: str
        """

        self._modified_date = modified_date
